# Changes here will be overwritten by Copier
_commit: 0.6.1
_src_path: https://github.com/nlesc/python-template.git
copyright_holder: Maeve Murphy Quinlan
email: earmmu@leeds.ac.uk
full_name: Maeve Murphy Quinlan
github_organization: murphyqm
keywords: desserts, pastry, sweets
license: MIT
package_name: baklava
package_short_description: dessert package
template_profile: minimum
version: 0.1.0
